### ISSUE TITLE
pragma omp parallel  bug

### ISSUE THREAD

**Issue by azzoti** [jianboqi/CSF#15]
I believe this code is wrong for  omp 
See https://github.com/CloudCompare/CloudCompare/issues/909 where same problem is reported for the CSF cloud compare plugin
```
#pragma omp parallel for
    for (int i = 0; i < particleCount; i++) {
        if (particles[i].isMovable()) {
            double diff = fabs(particles[i].old_pos.f[1] - particles[i].pos.f[1]);

            if (diff > maxDiff)
                maxDiff = diff;
        }
    }
```

**Comment by jianboqi** [comment]
Hello azzoti,
   Thank you very much for report this problem. It is really nor worth to use openmp for finding a maximum value, I have removed the OpenMP directive.
   Thank you!
