### ISSUE TITLE
可以读取pcd与bin格式的点云文件吗

### ISSUE THREAD

**Issue by lilywei888** [jianboqi/CSF#16]
readme里写了读取txt和las文件的方法，请问pcd和bin文件等格式怎么读取？

**Comment by jianboqi** [comment]
这两个不能支持噢，因为pcd是pcl库专用格式，需要pcl的支持，这个你可以自己实现，为了保持csf的简洁，目前没有引入第三方库的（如pcl）的打算。bin可能是二进制，需要自己去解析，

**Comment by lilywei888** [comment]
> 这两个不能支持噢，因为pcd是pcl库专用格式，需要pcl的支持，这个你可以自己实现，为了保持csf的简洁，目前没有引入第三方库的（如pcl）的打算。bin可能是二进制，需要自己去解析，

好的，谢谢。
