### ISSUE TITLE
infinite loop and high memory usage

### ISSUE THREAD

**Issue by spono** [jianboqi/CSF#18]
Hi,
as reported in [bug #8](https://github.com/Jean-Romain/RCSF/issues/8), CSF gets stuck while classifying a pretty regular point cloud: memory usage increases a lot and it gets into an infinite loop.
If you can provide a valid email address I can send you the test-file.
thanks!

**Comment by jianboqi** [comment]
Hi, Thank you very much for reporting the issue. please send me he test file to jianboqi@126.com.
I will check this problem. Thank you
