### ISSUE TITLE
Using CSF in Python

### ISSUE THREAD

**Issue by Cova88** [jianboqi/CSF#22]
I am trying to use CSF from Python 3.7 and I am not able to download the source code under python folder with the lines:

`python setup.py build
python setup.py install`

because I get this error message:  Unable to find vcvarsall.bat

As a consequence I can´t use the CSF.py script. I am really interested in filtering a lidar point cloud data with this method but I don´k now how to continue. I have tried also creating and environment in Python 2.7 and I hava the same problem.Any help?

**Comment by jianboqi** [comment]
Hello, I never test visual c++ 2008, which may be too old for me. I tried visual studio 2013, 2017 etc. there is no problem. Usually vcvarsall.bat is not found because the the compiler is not found. Can you just try new version?
