### ISSUE TITLE
Is is possible to get the cloth

### ISSUE THREAD

**Issue by Jean-Romain** [jianboqi/CSF#27]
Hi, I'm wondering if it is possible to return the cloth i.e. return the coordinates of the nodes programmatically. There is a an option `exportCloth` in `CSF::do_filtering` but it seems to write something in file. I'd like to get a C++ object I could transform into a raster in R. I can modify the code if needed.
Thanks.

**Comment by yulongyu** [comment]
when you dont give the params,exportCloth will equal false,you can change the code ,let it alway equal true 

	if (argc == 2 && strcmp(argv[1], "-c")==0)
	{
		std::cout << "Export cloth enabled." << std::endl;
		csf.do_filtering(groundIndexes, offGroundIndexes, true);
	}
	else
	{
		csf.do_filtering(groundIndexes, offGroundIndexes,false);//**change false to true**
	}

**Comment by Jean-Romain** [comment]
@yulongyu I don't want to write the cloth in file. I want to get it in a C++ object at runtime.

**Comment by yulongyu** [comment]
it is a vector<point> xyz , i dont know what is you meaning, you what use it in R language?

**Comment by Jean-Romain** [comment]
https://github.com/Jean-Romain/RCSF I want to return the cloth without writing a file.

**Comment by yulongyu** [comment]
in csf.h , std::vector<Particle> particles //it saved the cloth

**Comment by yulongyu** [comment]
i know what you want to do ...... but i think it is not recommend to return a lot points to another language as parameter，In a nutshell, your question is how to pass complex types to another programming language
