### ISSUE TITLE
How to generate the DTM with the ground points?

### ISSUE THREAD

**Issue by cangtian001** [jianboqi/CSF#29]
Hi, guys! This is really a good method. I have separeted the ground points and the object points.  Could you tell me how to generate the DTM with the ground points?

**Comment by jianboqi** [comment]
Hello,
   It it nice to hear that CSF helps your work, however, the major task of this project is to separate ground points from non-ground points, as for the generation of DTM with the ground points, it is not the task of CSF. There should be other software that can do this kind of job, like cloudcompare, etc.
Thank you
