### ISSUE TITLE
PCD file

### ISSUE THREAD

**Issue by jhjun724** [jianboqi/CSF#31]
Hi!
Is it possible to set input as '.pcd' files(3D point cloud data) and also get output as '.pcd' file?
Or do I have to convert '.pcd' to '.txt' or '.cfg'? 
And if it is possible, could you let me know how to handle it?
Thank you!

**Comment by jianboqi** [comment]
Hello, 
     supporting different format is not the major task of csf, since it only provides a few functions to do ground filtering. if you are using c++ or python or matlab to invoke csf, you can read pcd file into array by yourself , and feed this array into csf. If you just want to use csf as a commandline executable to process your pcd files,  you can use the csfdemo, but you should translate pcd into txt. or you can use csf plugin in cloudcompare. Thank you.
