### ISSUE TITLE
关于ISPRS数据集复现出现的一些问题

### ISSUE THREAD

**Issue by laiming997** [jianboqi/CSF#34]
使用开源的代码和论文所说的参数对ISPRS数据集进行测试，已提前对ISPRS的原始点云进行了统计学滤波过滤低点了，但是一类误差和论文所述差距很大，请问会是什么原因导致的呢

**Comment by jianboqi** [comment]
原始版本的程序再github开源之后，为了提高计算效率，减少库依赖，很多方面都有过修改了，现在不需要任何外部库。修改之后没有再用ISPRS数据进行测试测试，如果要复现文章结果的话，可以使用最早的原始代码。已经通过邮箱发给你了，你可以试试。

**Comment by laiming997** [comment]
非常感谢您提供的源码，我对比了下与现在github上的区别，其中在raster和赋予内部作用力，即rigidness有区别。我对您提供的源码进行了编译，因为提供的lib是release的无法debug，跑出来的效果更差了无法查看什么原因，请问下您这份代码是当时跑的那份嘛，非常感谢



我的交大在 jianboqi <notifications@github.com>，2021年1月3日 上午10:35写道：
原始版本的程序再github开源之后，为了提高计算效率，减少库依赖，很多方面都有过修改了，现在不需要任何外部库。修改之后没有再用ISPRS数据进行测试测试，如果要复现文章结果的话，可以使用最早的原始代码。已经通过邮箱发给你了，你可以试试。

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/jianboqi/CSF/issues/34#issuecomment-753558678",
"url": "https://github.com/jianboqi/CSF/issues/34#issuecomment-753558678",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by jianboqi** [comment]
最原始的代码找不到了，不过给你的这个代码是根据之前部分代码恢复的。我这边之前有人测试过，这个结果还是比较接近文章里的，这个就是给你的那个代码编译的，你可以试一下。

[test.zip](https://github.com/jianboqi/CSF/files/5770810/test.zip)

**Comment by laiming997** [comment]
您好，你给我的压缩包了是个可执行文件，您说这个可执行文件时您前几天发给我的CSF-原始源码.zip压缩包编译后的吗？我执行了一下这次压缩包里的可执行文件，发现Rasterizing的时候有raster1、raster2、raster3，是不是对地形根据起伏进行了3个
量级的分区，这部分代码在之前的压缩包里好像没有体现。我的问题比较多，因为最近毕业论文基于你们工作之下的，时间比较着急，所以一直打扰到您，非常抱歉，也非常感谢您的耐心指导。

----- 原始邮件 -----
发件人: "jianboqi" <notifications@github.com>
收件人: "jianboqi/CSF" <CSF@noreply.github.com>
抄送: "laiming997" <ming997@sjtu.edu.cn>, "Author" <author@noreply.github.com>
发送时间: 星期二, 2021年 1 月 05日 下午 10:51:08
主题: Re: [jianboqi/CSF] 关于ISPRS数据集复现出现的一些问题 (#34)

最原始的代码找不到了，不过给你的这个代码是根据之前部分代码恢复的。我这边之前有人测试过，这个结果还是比较接近文章里的，这个就是给你的那个代码编译的，你可以试一下。

[test.zip](https://github.com/jianboqi/CSF/files/5770810/test.zip)

**Comment by jianboqi** [comment]
我们这边测试了，没有发现什么raster1，raster2之类的，你可以直接发邮件吧，沟通更方便一些，发我们一个截图jianboqi@126.com 看看是什么问题。
