### ISSUE TITLE
D8021 invalid numeric argument '/Werror' CSF

### ISSUE THREAD

**Issue by Matt-V50** [jianboqi/CSF#36]
Is there one have seen this error before when build solution?

**Comment by jianboqi** [comment]
Hi,
I just noticed that there is a problem when building on Windows, you can remove /Werror option:
    target_compile_options(CSF PRIVATE -Werror -Wall -Wextra)
When building on windows, you can remove this line in src/CMakeLists.txt

**Comment by Crghilardi** [comment]
@FavorMylikes Would you be able to test the fix in [this commit](https://github.com/jianboqi/CSF/pull/38/files) and see if that fixes it? I do not have access to a Windows machine currently

**Comment by Matt-V50** [comment]
@Crghilardi Seems ok, I replace `/Werror to /W4`, and remove  `/Wextra` manually.

I use cmake to build vs solution, and not find where the code is.

Here is what I changed at `CSF/CMakeList.txt`.

```cmake
if(OpenMP_CXX_FOUND)
    target_link_libraries(CSF PUBLIC OpenMP::OpenMP_CXX)
    target_compile_options(CSF PRIVATE -W4 -Wall)
endif()
```
