### ISSUE TITLE
Using CSF with velodyne data

### ISSUE THREAD

**Issue by mdemirst** [jianboqi/CSF#5]
Is your algorithm mainly developed for airborne scan data? Can I use it for segmenting out ground points from pointcloud constructed with velodyne placed on top of the vehicle? Which parameters need to be changed?

**Comment by jianboqi** [comment]
Hello mdemirst,
   we have tested our algorithm on terrestrial lidar and also vehicle-based lidar, it works fine. Usually, it does not need special parameters to segment ground and non-ground points. You can try with the default parameter.
The most convenient way to try with CSF is to use the plugin implemented in Cloudcompare. This can tell you whether CSF suits your requirements.
