### ISSUE TITLE
Varying results even without multithreading

### ISSUE THREAD

**Issue by SabineZa** [jianboqi/CSF#52]
Hello,

I want to use the CSF for my Master's Thesis but unfortunately I have some problems with varying results. My point cloud has in total 23,146,900 points and here are some results for example:

```
Number of non-ground points: 14675441
Number of ground points: 8471459

Number of non-ground points: 14632410
Number of ground points: 8514490

Number of non-ground points: 14591098
Number of ground points: 8555802

Number of non-ground points: 14595535
Number of ground points: 8551365

Number of non-ground points: 14595098
Number of ground points: 8551802

Number of non-ground points: 14592757
Number of ground points: 8554143
```

Since the answer to issue #21 said that the problem can be caused by multithreading, I first added `os.environ["OMP_NUM_THREADS"] = "1"` in my code. I didn't noticed any change in the results, so I tried to fork the repository and excluded all omp calls from the code (https://github.com/SabineZa/CSF). Unfortunately, I have still the same variations in my results, so I believe the non-deterministic results aren't caused by multithreading. I also tried it with different point clouds and examined the results from the CloudCompare plugin, which show the same behavior. 
Is there an explanation why I always get different results? Is it supposed to be like this? Is it possible to get stable results? In order to use it in a scientific way I need reproducible results. 
Thanks in advance and I would appreciate any advice to help me with my problem.

**Comment by jianboqi** [comment]
Hi, I have test this issue, to disable the openmp, you can simply remove the three lines from the setup.py file:
```
extra_compile_args=openmp_args,
extra_link_args=openmp_linking_args,
define_macros=openmp_macro
```
I tested the filtering results before and after removing this three lines, the results show that after removing the openmp, the filtering results is stable:
```
Num of ground points: 53971
Num of non-ground points: 119275

Num of ground points: 53971
Num of non-ground points: 119275

Num of ground points: 53971
Num of non-ground points: 119275
```

If openmp is enabled, the results is the same as yours:
```
Num of ground points: 53912
Num of non-ground points: 119334

Num of ground points: 53900
Num of non-ground points: 119346
```
So, I am sure the this issue is caused by the openmp. You can try what I have done. And also, if  you are using some ide, please make sure whether they have some caches. Or, have you properly installed the version without openmp, sometimes caches matters.

**Comment by SabineZa** [comment]
Hi,
thank you very much for your fast response and your help! You are totally right: The issue is caused by openmp. After removing the three lines that you mentioned from the setup.py file, I also get stable filter results. I guess that I didn't disable openmp completely in my previous attempts.
