### ISSUE TITLE
why use gravity like drop process?

### ISSUE THREAD

**Issue by riyueshi** [jianboqi/CSF#6]
Hi, jianboqi
  I am curious what is the reason CSF using gravity like drop process? In order to hit the ground faster? Or is there any other reason using this model?
 Miller

**Comment by jianboqi** [comment]
Hi Miller,
    We use gravity just to simulate the process that cloth drops to the ground, which is more natural and easier to understand by users. Because what we want to do is to fit the cloth with the shape of the terrain, this process just looks like a cloth drops to the ground (inverted).

**Comment by riyueshi** [comment]
Thanks, but I think using gravity to compute the step dosen't have any help for user to understand. And this may result in very big drop step if the points contain outlier.
