### ISSUE TITLE
How to get Index of Ground points from input XYZ list?

### ISSUE THREAD

**Issue by Tejuwi** [jianboqi/CSF#7]
Thank you very much for your code. I am able to separate the ground and non-ground and visualize it. Works very well. I would like to apply classification algorithm for non-ground points. I have to extract the index of non ground points.

From your example: 
inFile = laspy.file.File(r"in.las", mode='r')
points = inFile.points
xyz = np.vstack((inFile.x, inFile.y, inFile.z)).transpose()

How can I get the ground point index from xyz list?

Thanks again

**Comment by jianboqi** [comment]
Hello, 
    the ground and non-ground index of points can be obtained when you finish the filtering process.
ground = CSF.VecInt()  # a list to indicate the index of ground points after calculation
non_ground = CSF.VecInt() # a list to indicate the index of non-ground points after calculation
csf.do_filtering(ground, non_ground) # do actual filtering.

After do_filtering, the two lists: ground and non_ground stores the index of ground and non-ground points, respectively. Then you can get all the non-ground points simply by non_ground_xyz = xyz[non_ground]
I hope I have understood your question well.
Thank you
Jianbo

**Comment by Tejuwi** [comment]
After looking at non-ground points, I am expecting the position of row number(Index)of xyz but getting x,y and z values. 

example:
X            Y        Z
10.1     12.1      1
10.2     12.1      1.2
10.4     12.3      4.1
10.1     12.2      1.1

after your algorithm and Non-ground extraction, I am getting   x,y,z value (10.4     12.3    4.1)  but i am expecting index 3. It is easy for me to apply classification technique on non ground points, To get it, I have to convert ground points into DEM for estimate height model. Any suggestions would be great help.

Thanks

**Comment by jianboqi** [comment]
After the filtering process, the vector non_ground is exactly the index (i.e., the row number in xyz).
What I means that the function after the execution of  csf.do_filtering(ground, non_ground) 
non_ground stores the index.
example:
X Y Z
10.1 12.1 1
10.2 12.1 1.2
10.4 12.3 4.1
10.1 12.2 1.1

if (10.1 12.1 1) and (10.4 12.3 4.1) are the non-ground points, then non_ground stores 1 and 2 (the index starts from 0).  So no spectial operation is needed, the output is what you want

**Comment by Tejuwi** [comment]
Thank you for your time. I am working on classification of non ground points (Buildings and trees etc) and then need to combine both ground and non ground points.so need to track of index of xyz. 

Also noticed loosing values due to CSF.VecInt().  
My orginal las values of xyz is 
       [  4.93499921e+05,   6.95055318e+06,   2.27980000e+01],
       [  4.93499982e+05,   6.95055343e+06,   2.29620000e+01],

processed ground values 
       [493499.90625000	6950553.00000000	22.79800034]
       [493499.96875000	6950553.50000000	22.96199989]
due to this problems my las boarders are changing.

If I know the index of xyz(ground or non ground), I can get the original values(xyz)

Kindly help me for the above issue. 
Separate ground and non ground points results are really good and it is very faster than other methods.
